name: Clojure With Minikube

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Setup Minikube
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.7.2
      with:
        minikube version: 'v1.28.0'
        kubernetes version: '1.24.12'
        github token: ${{ secrets.GITHUB_TOKEN }}
    # Setup Clojure
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
